[package]
name = "string-wrapper"
version = "0.1.4"
authors = ["Simon Sapin <simon.sapin@exyr.org>"]
license = "MIT / Apache-2.0"
repository = "https://github.com/SimonSapin/rust-std-candidates"
description = "A String with generic bytes storage"

[lib]
path = "lib.rs"
doctest = false
